### ISSUE TITLE
画面遷移図を作る

### ISSUE THREAD

**Issue by bbbbruno** [brutex/ranking-memo#2]
## 目的
必要な画面数を把握すること。

## ゴール
必要な画面を洗い出し、画面遷移図を作成する。
Wikiにまとめる。

## TODO
- [ ] [必要な画面の洗い出し · Issue #13 · brutex/ranking-memo](https://github.com/brutex/ranking-memo/issues/13)
- [ ] [画面遷移図の作成 · Issue #14 · brutex/ranking-memo](https://github.com/brutex/ranking-memo/issues/14)
- [ ] [Wikiにまとめる · Issue #15 · brutex/ranking-memo](https://github.com/brutex/ranking-memo/issues/15)
